version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin#2024sql"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./db/init-db.sh:/usr/src/app/init-db.sh # Monta el script de inicialización
    entrypoint: ["/bin/bash", "-c", "/usr/src/app/init-db.sh"] # Asegura la ejecución del script

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: deliveryapp
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://db:1433;databaseName=DeliveryApp;encrypt=true;trustServerCertificate=true;"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "Admin#2024sql"
    command: ["sh", "-c", "./wait-for-it.sh db:1433 -- java -jar app.jar"]
    ports:
      - "8080:8080"

  drawweb:
    build:
      context: ./drawweb
      dockerfile: Dockerfile
    container_name: drawwebaplication
    ports:
      - "8085:80"

volumes:
  sql_data:
