FROM eclipse-temurin:22-jdk AS builder

WORKDIR /app
COPY . .

RUN chmod +x gradlew
RUN ./gradlew bootJar

FROM eclipse-temurin:22-jdk

WORKDIR /app

COPY --from=builder /app/build/libs/DeliveryApp-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
