FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

COPY init-db.sh /usr/src/app/init-db.sh
COPY schema.sql /usr/src/app/schema.sql
COPY data.sql /usr/src/app/data.sql

RUN chmod +x /usr/src/app/init-db.sh

USER mssql

ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer

ENTRYPOINT ["/usr/src/app/init-db.sh"]
